name: Rust CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: production-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_DIR: "Authentication System with 2FA"

jobs:
  # ==========================================================
  # CI
  # ==========================================================
  ci:
    name: CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            Authentication System with 2FA -> target

      - name: Check Rust version
        run: |
          rustc --version
          cargo --version

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --locked --all-targets --all-features

      - name: Run tests
        run: cargo test --locked --all-features

      - name: Run Clippy
        run: cargo clippy --locked --all-targets --all-features